# Linux setup Kubuntu

# Installation

* Shrink Windows partition ( [Problems](https://superuser.com/questions/1017764/how-can-i-shrink-a-windows-10-partition) )
* Boot from USB
    - [Create USB Stuck on Windows](https://ubuntu.com/tutorials/create-a-usb-stick-on-windows#1-overview)
    - [Installation from USB Stick (Quick version)](https://help.ubuntu.com/community/Installation/FromUSBStickQuick)
    - [Installation from USB Stick](https://help.ubuntu.com/community/Installation/FromUSBStick)
* Define partitions
    - SWAP, no mount point, 10GB, Primary,
    - root, mount: /, 40GB, Primary, ext4
    - home, mount: /home, as much as possible, Primary, ext4
    

# KDE Wallet

* Usually KDE Wallet is prompted at startup
* Avoid by creating an empty wallet password (insecure!)
  - System Settings > Account Details > KDE Wallet > Click "Launch Wallet Manager"
  - Click "Change Password"
  - Click "OK" without inserting a password
  - Details
    + [Manjaro Forum](https://forum.manjaro.org/t/bug-kde-wallet-is-asking-for-password-on-every-boot/33415)
    + [Unix Stackexchange](https://unix.stackexchange.com/questions/420497/how-do-i-stop-kwallet-from-asking-my-password-to-let-the-system-connect-to-wifi)

# Some configurations (New since ETH Computer)

* Avoid open file/folder with single click
  - `System Settings` > `Workspace Behavior` > `General Behavior` > Click:behavior: Double-click to open files and folders
* Avoid special behaviour of left screen corner (Toggle Present Windows, All desktops)
  - Same can be called with Ctrl+F10 or maybe set it manually to Alt+Q (next to Alt+tab for switching windows)
* Activate Compose key
  - `Input Devies` > `Keybord` > `Advanced` > `Configure keyboard options` > `Position of Compose key` > `Caps Lock`


# Easy tasks

1. Setup external screen
2. Install software
    - From Software Center
        + Kile
        + ownCloud desktop sync client (Polybox)
        + gscan2pdf
        + Steam installer
        + Inkscape
        + Kamoso (Webcam)
        + KColorChooser (Screen Color selection)
        + KolourPaint
    - From downloaded tar
        + Google Chrome
        + R Studio
        + Zotero (maybe better use )
    - From Konsole
        + `sudo apt install git-all` (For configuration see git chapter)
        + `git lfs install` (For git large files storage)
        + `sudo apt-get install network-manager-vpnc` (for vpn connections)

# Installing R

See [It's FOSS](https://itsfoss.com/install-r-ubuntu/), [R Documentation](https://cran.r-project.org/bin/linux/ubuntu/README.html), and [R Ubuntu Blog](https://rubuntu.netlify.app/)

1. Add CRAN repository to apt (Exact command depends on Ubuntu version)

```bash
deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/
```

2. Add key to repository

```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
```

3. Update and install

```bash
sudo apt update
sudo apt install r-base
```

UPDATE 2021: I guess, the process is slightly different now. See

* [Official R project instructions](https://cran.r-project.org/bin/linux/ubuntu/)
* [RStudio instructions](https://docs.rstudio.com/resources/install-r/)

The RStudio instructions might be better if you need multiple versions of R.

* [Here](https://support.rstudio.com/hc/en-us/articles/360002242413-Multiple-versions-of-R) it says 'To get multiple versions of R side-by-side, it's important that you do not use your linux package manager to install R. For example, do not use apt (Debian or Ubuntu). When you install R from these package repositories, you will overwrite your existing R version, and your old version of R will no longer be available.'
* Now have two options
  - Install precompiled binary from RStudio Server
    + Fast
    + Recommended
  - Install R from source
    + Time consuming
    + More customizable

# Remap Keyboard

Alternative:

* Use a [Compose Key](https://userbase.kde.org/Tutorials/ComposeKey)
    + Now I think this would acctually be the better option!
    + [Compose Key cheat sheet](https://tuttle.github.io/python-useful/compose-key-cheat-sheet.html)
* [EurKey](https://eurkey.steffen.bruentjen.eu/)

Original setup

1. Go to Software center and install 'AutoKey (Qt)'
2. Open AutoKey ( [Tutorial](https://www.maketecheasier.com/autokey-make-your-own-keyboard-shortcuts-in-linux/) )
3. Click on `New...` > `Folder` and name it e.g Umlaute
4. Make 6 new `Phrase` within that folder and name them ae, Ae, oe, Oe, ...
5. In the text field put the desired Character
6. Set a hotkey (e.g. alt+')

Problem: Capital umlaute are made small. Fix: Add some Emoji after the capital Umlaut.

Problem: Autokey shows up at startup. Fix: [Exclude Autokey from startup session](https://github.com/autokey/autokey/wiki/Troubleshooting#autokey-qt--kde-desktop-automatically-starting-autokey-shows-the-gui-during-login-even-if-show-main-window-when-starting-is-disabled)

Next: Remap Caps Lock to Hyper Key

1. `System Settings` > `Imput Devices` > `Keyboard` > `Advanced` > `Caps Lock behavior` > Make Caps Lock an additional Hyper
2. Reboot




# Installing Latex

1. Uninstall preinstalled light TexLive with commands found on [StackOverflow](https://tex.stackexchange.com/questions/95483/how-to-remove-everything-related-to-tex-live-for-fresh-install-on-ubuntu)
2. Install [TinyTeX](https://yihui.org/tinytex/) from R console
3. Add TinyTeX Built to Kile
    - Open Kile
    - `Settings` > `Configure Kile` > `Build`
    - Select a tool: `New...`
    - Name: RZTinyTeX
    - Class: <Custom>
    - General: Command: Rscript
    - General: Options: -e "tinytex::pdflatex('%source')"
4. Configure Shortcut for pdflatex and RZTinyTex
5. Install biber `sudo apt install biber`

**Alternative: (maybe better)**

Just install texlive-latex-extra which contains most packages... less problems... [Installation guide](https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux)

Even better: Install "vanilla" Tex Live: https://tex.stackexchange.com/a/95373/202258

Here the reason why "vanilla" could be better: https://tex.stackexchange.com/a/200216/202258

To install a specific package: https://tex.stackexchange.com/a/73017/202258

As an example you might want to try to install package `siunitx`



# Installing AOE2

See this [reddit article](https://www.reddit.com/r/aoe2/comments/aa6lry/aoe2hd_on_debian_linux_via_steam_play_tutorial/). Step 2, 3 and 4 were enought.

1. Install steam from Software center
2. Settings > Steam Play > Enable Steam Play for all other titles
3. Install
4. Right click on Game in steam > Properties > Set Launch options > type '-nostartup'



    
# Set up Backup

See separate Chapter\ \@ref(sec:backup) about backups.

# Dualboot with Windows

* Select which OS to boot
    - At startup press some F key
    - Depends on hardware, for ThinkPad X230
        + `Enter` Choose one of the below options (more time to choose and explanation text)
        + `F1` Enter Bios setup utilit (Change default computer/Bios settings)
        + `F10` Diagnose hardware (never used so far)
        + `F12` Choose temporary startup device
    - Depending where the OS is saved you have to choose from where to boot
    - Currently
        + Kubuntu: ATA HDD2: ADATA SX300
        + Windows: ATA HDD0: HGST HTS725050A7E630
* Don't show GRUB GUI at startup
    - See [here](https://linoxide.com/linux-how-to/hide-grub-boot-linux/)
    - Open `/etc/default/grub`
        + Change: `GRUB_TIMEOUT=0`
        + Add line: `GRUB_DISABLE_OS_PROBER=true`
    - Open shell and run `sudo update-grub`


# Troubles

## Locales

### New

* Set LANG to en_US.UTF-8
* Set Formats to de_CH.UTF-8 (NOT en_US.UTF-8)
* add file `.Renviron` to home directory with content `LANGUAGE="en_US.utf8"`




### Old Way:

Only necessary when Regional settings: Switzerland en

Some actions at Konsole might give error 'perl: warning: Setting locale failed.'

See solution [here](https://libre-software.net/ubuntu-setting-locale/)

Check which local settings are missing

```bash
locale
```
Might return 'locale: Cannot set LC_ALL to default locale: No such file or directory'

The solution is to export the missing locales to ~/.bash_profile. The following command is a one-command line:

```bash
echo "export LANGUAGE=en_US.UTF-8 export LANG=en_US.UTF-8 export LC_ALL=en_US.UTF-8">>~/.bash_profile
```

## DVD

See [It's FOSS](https://itsfoss.com/play-dvd-ubuntu-1310/)

```bash
sudo apt install libdvd-pkg
sudo dpkg-reconfigure libdvd-pkg
```

In between always click OK/Yes.


## Scrolling with touchpat

* Kinetic scrolling is not enabled with default driver
* Solution: use another driver
    - Open Terminal
    - `sudo apt install xserver-xorg-input-synaptics`
    - reboot
    - go to `System settings` > `Input Devices` > `Touchpad`
    - In `Scrolling`
        + Enable two-finger scrolling (vertical and horizontal)
        + Enable reverse scrolling
    - In `Pointer Motion
        + Adjust speed

## During shutdown, computer goes to sleep mode if lid is closed

* `System Settings` > `Power Management` > `Energy Saving` > When laptop lid closed: Turn off screen
        

## Search in Dolphin is slow

* Make sure your search engine is baloo
* `System Settings` > `Search` > `File Search` > Do not search in these locations
    - exclude Drives which you want to index
* `System Settings` > `Search` > `File Search` > Also index file content
    - If you want to search for content within pdfs, text files, ...



# Useful software

* From Software Center
    - GIMP
    - Xournal (Handwritten notes, sign)
        + [How can I add a signature to a PDF](https://unix.stackexchange.com/questions/85873/how-can-i-add-a-signature-png-to-a-pdf-in-linux)
    - Julia
    - KBackup
* Via apt
    - kup-backup
* Other
    - [MineTime calender](https://minetime.ai/)

# Inkscape

* Install inkscape (Software Center or `sudo apt-get install inkscape`)
* Read [TexText 1.0 Docs](https://textext.github.io/textext/install/linux.html) to be able to use latex in inkscape
    - I was necessary to run `python3 setup.py` instead of `python setup.py` during installation...


# Maybe useful

* `System Settings` > `Imput Devices` > `Keyboard` > `Hardware` > NumbLock Turn on
* `ownCloud` > `General` > `Edit Ignored Files` > `Add` > '.Rproj.user'
* install Computer Modern font (for same font as latex pdf documents) with `sudo apt install fonts-cmu`


# Connect with Phone

* [scrcpy](https://github.com/Genymobile/scrcpy)
    - If slow USB connection: limit resolution with `scrcpy -m 1920`
* [IP Webcam](https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en&gl=US)
* KDE Connect


# Mouse middle click scrolling (Auto-Scrolling)

See [here](https://unix.stackexchange.com/questions/58900/how-to-scroll-the-screen-using-the-middle-click/421672#421672)

However,

- it scrolls too slow.
- Dagerouse that something is pasted (Mouse middle click is still paste)
- Maybe don't use it...

# Logitech Mouse

Logitech Unifying Receivers for Linux [Solaar](https://pwr-solaar.github.io/Solaar/)

* Download from Discover
* Add devices

